# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 11:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('job_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('family_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('income_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('expenses_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('stage', models.CharField(choices=[(b'initial', b'Initial'), (b'secondary', b'Secondary')], default=b'initial', max_length=20)),
                ('status', models.CharField(choices=[(b'approved', b'Approved'), (b'declined', b'Declined'), (b'problem', b'Problem'), (b'pending', b'Pending')], default=b'pending', max_length=20)),
                ('guarants', models.ManyToManyField(to='kik.Person')),
                ('renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='kik.Person')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='kik.Person'),
        ),
        migrations.AddField(
            model_name='form',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='kik.Request'),
        ),
    ]
