# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kik', '0003_auto_20151220_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='guarants',
            field=models.ManyToManyField(blank=True, null=True, to='kik.Person'),
        ),
    ]
