# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 13:17
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kik', '0004_auto_20151220_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 21, 19, 17, 10, 600710)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 12, 21, 19, 17, 25, 629070)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 21, 19, 17, 36, 169351)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 12, 21, 19, 17, 37, 928240)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='credit_manager_conclusion',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 21, 19, 17, 39, 345236)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 12, 21, 19, 17, 40, 958111)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='lawyer_conclusion',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='risk_conclusion',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='security_conclusion',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
