# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kik', '0005_auto_20151221_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='document_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
