# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 18:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kik', '0007_auto_20151222_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='lpk',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='msap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='guarants',
            field=models.ManyToManyField(to='kik.Person'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[(b'approved', b'Approved'), (b'declined', b'Declined'), (b'problem', b'Problem'), (b'pending', b'Pending'), (b'approved_by_rc', b'Approved by rent committee'), (b'declined_by_rc', b'Declined by rent committee')], default=b'pending', max_length=20),
        ),
    ]
