# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kik', '0008_auto_20151222_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='gcvp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
